### ISSUE TITLE
How to cite this work?

### ISSUE THREAD

**Issue by KajiMaCN** [Harshs27/Q-Classifier#1]
How to cite this work?

**Comment by Harshs27** [comment]
@inproceedings{shrivastava2015classification,

  title={Classification with imbalance: A similarity-based method for
predicting respiratory failure},
  author={Shrivastava, Harsh and Huddar, Vijay and Bhattacharya,
Sakyajit and Rajan, Vaibhav},
  booktitle={2015 IEEE international conference on bioinformatics and
biomedicine (BIBM)},
  pages={707--714},
  year={2015},
  organization={IEEE}
}
